### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by Zar-khan** [mohhamad-esmaili/mindwrite#1]
I run this repository but there is a language issue. Can you help me resolve this?
![image](https://github.com/user-attachments/assets/24b8f0bd-8384-47c1-bd04-73fcd75009ba)

**Comment by mohhamad-esmaili** [comment]
Hi, sorry about language problem, this app is released and published for Iranian stores so the default lan is persian, but you can change here:
Go to drawer on right side (three line icon)
![Uploading Screenshot_20241124-230624.jpg…]()

**Comment by mohhamad-esmaili** [comment]
Hi,
Sorry about that, the app is released for Iranian users so the lang is persian by default, but you can change it like:
<div style="display: flex; justify-content: space-around;">
  <img src="https://github.com/user-attachments/assets/a3143502-24d4-45a3-85de-6f05dcd5a65a" alt="Image 1" width="150" />
  <img src="https://github.com/user-attachments/assets/9680bbd0-5066-4a73-8964-928d3c36c90b" alt="Image 2" width="150" />
  <img src="https://github.com/user-attachments/assets/310afac9-c68b-4dc1-bfbc-8284222d6432" alt="Image 3" width="150" />
</div>
